//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        public int Id { get; set; }
        [Required]
        public string First_name { get; set; }
        [Required]
        public string Last_name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [RegularExpression("([0-9]+)", ErrorMessage = "Phone Number must be 10 Digits Long.")]
        public int Phone { get; set; }
        public string Photo { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Date_of_birth { get; set; }
        public int Age { get; set; }
        [Required]
        public string Blood_group { get; set; }
        [Required]
        public string Father_name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public int Driving_license_number { get; set; }
        [Required]
        public string Category { get; set; }
        //[Required]
        public string Date_of_issue { get; set; }
        public string Validity { get; set; }
        public string Issuing_authority { get; set; }
        public string Is_wanted { get; set; }
    
        public virtual Info_offences Info_offences { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
