//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Surgeon
    {
        public int Id { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Zone { get; set; }
    
        public virtual Info_offences Info_offences { get; set; }
    }
}
